name: Palace
favicon: null
layout_spectrum: 0.5764691145159304
typography_spectrum: 0.7992443817202002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6752962074242532
  lightness: 0.85126982210204
  saturation: 0.2133788475766778
  rhythmicContrast: 0.03128522145561874
purpose: []
